### ISSUE TITLE
Unhandled promise rejections

### ISSUE THREAD

**Issue by olliebrennan** [theiconic/zoomstats#16]
Hey hey!

I'm having trouble getting this to work. Wondering if the source of the recording page has changed :( 

Was out the box, checkedout, npm installed and tried to run. Tried a few of the different options with no avail.

```
$ node src/index.js talktime roadmapchat.htm
analyzing file roadmapchat.htm
(node:83746) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getAttribute' of null
    at module.exports.document (/Users/obrennan/workspace/zoomstats/src/parser/html.js:7:58)
    at JSDOM.fromFile.then.dom (/Users/obrennan/workspace/zoomstats/src/util/parse-html-file.js:6:12)
(node:83746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wyrfel** [comment]
@olliebrennan Oh hello. 😄  I'll have a look. It's quite possible the HTML has changed, thanks for reporting.

**Comment by wyrfel** [comment]
@olliebrennan Unfortunately, the whole way the page loads has changed with the transcript now being ajax-loaded, so the old procedure of saving the page and then using zoomstats in CLI mode doesn't work anymore and is not easy to fix.
I'm fixing up the chrome extension, although they are also not exposing as much data anymore. Would the chrome extension be useful to you?

**Comment by olliebrennan** [comment]
Hello @wyrfel! 👋Yes, the Chrome extension would be useful!

Zoom also has the VTT files for download to get the raw transcript if you can use that instead.

**Comment by wyrfel** [comment]
@olliebrennan I know it's been a while, but I've finally gotten around to make some updates and it's working again, now. In the past I couldn't use the VTTs because they didn't include the speaker names. However, now they do - so yay!

Both the tool and the extension now use the VTTs. I've submitted the extension for public listing and it's awaiting approval. However, in the meantime you can play around with the command line tool.
